
name: guan

on:
  schedule:
    - cron: '55 14 * * *' # 每天UTC时间零点执行

jobs:
  curl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: guan
        run: |
          curl -X GET 'https://nb.quanqiuwa.com/api/integraldata/app/check-in/integral/946' \
          -H 'Host: nb.quanqiuwa.com' \
          -H 'Connection: keep-alive' \
          -H 'charset: utf-8' \
          -H 'channelno: 4TU6AVOEVQ' \
          -H 'x-qqw-channel-no: 4TU6AVOEVQ' \
          -H 'User-Agent: Mozilla/5.0 (Linux; Android 10; 24030PN60C Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 XWEB/1160083 MMWEBSDK/20231202 MMWEBID/5713 MicroMessenger/8.0.47.2560(0x28002F36) WeChat/arm64 Weixin Android Tablet NetType/4G Language/zh_CN ABI/arm64 MiniProgramEnv/android' \
          -H 'x-qqw-miniapp-testline: false' \
          -H 'Accept-Encoding: gzip,compress,br,deflate' \
          -H 'x-qqw-client-version: WxMiniApp-4TU6AVOEVQ-1.4.899' \
          -H 'x-qqw-request-sign: MFsXXhkd80p1yapGW40bQmY8hR9SyL2CSpdkZTl3HIs=' \
          -H 'x-qqw-request-nonce: ND353FjKwR' \
          -H 'x-qqw-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJBUFAiLCJpc3MiOiJTZXJ2aWNlIiwiZXhwIjoxNzE1MTQ5NjI5LCJpYXQiOjE3MTI1NTc2MjksImN1cnJlbnRfdXNlciI6IntcImNoYW5uZWxOb1wiOlwiNFRVNkFWT0VWUVwiLFwiY3VzdG9tZXJJZFwiOjMwNzU3NzcsXCJjdXN0b21lck5vXCI6XCIwOTQyc2M1QWJnTlZcIixcImxvZ2luQ2hhbm5lbFwiOlwiV0VDSEFUXCIsXCJvcGVuSWRcIjpcIm9PbG5VNUxZbTBCRUViUkU4NS0zVDN1M3MzdU1cIixcInNlc3Npb25LZXlcIjpcIktwc1lEWHVyR2NVUSs4SFJ4RUhVYnc9PVwiLFwidXNlcklkXCI6MTI4NDYxNTV9In0.c1jz-LnMptKlP8W9wyFfyPWcj2NZ7QtEyBGnfpbWrTE' \
          -H 'content-type: application/json' \
          -H 'x-qqw-miniapp-prono: 29arrive' \
          -H 'Referer: https://servicewechat.com/wxa7a8c8300c564800/155/page-frame.html' \
          --compressed
