name: wp

on:
  schedule:
    - cron: '1 4 * * *' # 每天UTC时间零点执行

jobs:
  curl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: wp
        run: |
          curl -X POST 'https://inf-prdapi.wesure.cn/prdapp/rpc/fan-benefit-activity/signIn' \
          -H 'Host: inf-prdapi.wesure.cn' \
          -H 'Connection: keep-alive' \
          -H 'Content-Length: 2' \
          -H 'charset: utf-8' \
          -H 'ws-route: pages/activity/gzhWelfare/home/index' \
          -H 'User-Agent: Mozilla/5.0 (Linux; Android 14; 2201122C Build/UKQ1.231003.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 XWEB/1160083 MMWEBSDK/20231202 MMWEBID/7437 MicroMessenger/8.0.47.2560(0x28002F36) WeChat/arm64 Weixin Android Tablet NetType/4G Language/zh_CN ABI/arm64 MiniProgramEnv/android' \
          -H 'Accept-Encoding: gzip,compress,br,deflate' \
          -H 'ws-loginid: oc2P70At5CQ8oP8uJo2RDXKeWDME' \
          -H 'ws-login-appid: wx06a561655ab8f5b2' \
          -H 'ws-miniapp-version: 5.2.7' \
          -H 'ws-login-token: 74506E75E40672890188D446B8A49A7F' \
          -H 'ws-proto-version: 3' \
          -H 'ws-login-type: 1' \
          -H 'ws-deviceid: 31057171060711430041475' \
          -H 'ws-sessionid: 99224171155115886041426' \
          -H 'ws-channel: ' \
          -H 'ws-request-id: vYZfxiAo' \
          -H 'ws-miniapp-env: prd' \
          -H 'ws-platform: wc-app' \
          -H 'content-type: application/json' \
          -H 'ws-scene: 1014' \
          -H 'ws-wtagid: N155.1.313' \
          -H 'Referer: https://servicewechat.com/wx06a561655ab8f5b2/1224/page-frame.html' \
          --data '{}' \
          --compressed
