name: Run 小兔
on:
  schedule:
    # 每天 11:01 UTC 时间运行
    - cron: '1 11 * * *'  # UTC 时间
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: python 小兔.py  # 替换为你的Python脚本文件名

      - name: Wait for a minute and run again
        run: |
          for i in {1..9}; do  # 运行9次（总共10次，包括第一次）
            sleep 60  # 等待60秒
            python 小兔.py  # 再次运行你的Python脚本
          done
